name: "Terraform-github"
on: 
  push:
    branches:
      - "master"

jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Export environment Variables
        run: |
          export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        shell: bash

      - name: Initialize terraform
        run: terraform init

      - name: Run terraform plan
        run: terraform plan -out

      - name: Apply the changes made
        run: terraform apply
