name: "Terraform-github"
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
env:
  TF_VAR_CLIENT: ${{ secrets.ARM_CLIENT_ID }}
  TF_VAR_SUB_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_TENANT: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Initialize terraforms
        run: terraform init -reconfigure

      - name: Terraform plan
        run: terraform plan -lock=false


      - name: Apply the changes made
        run: terraform apply --auto-approve

  destroy:
    needs: [create-resource]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Initialize terraform
        run: terraform init -reconfigure

      - name: Destroy resources
        run: terraform destroy -auto-approve

